# Generated by Django 3.0.3 on 2020-09-25 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareRes', '0002_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant_nlink',
            new_name='restaurant_link',
        ),
    ]
